# DCEConfig file
# Title: Kapsyljakt med Anki & Pytte
# MD5 (Anki och Pytte.exe): A077DAE51DB55329108D66E1E76F971F
# DCEAPIHook version: v0.6.0
# NOTE: During game installation select full install

loader:
  target: "Anki och Pytte.exe"
    
virtual_drives: ['l']

hooks:
  - api: "GetDriveTypeA"
    arg1: "l:\\"
    return: 5

directory_redirections:
  - source: "l:\\"
    destination: ".\\"
